### ISSUE TITLE
Running command fails with "read property 'id' of null"`

### ISSUE THREAD

**Issue by anthonator** [heroku/heroku-releases-retry#8]
We're getting the following error whenever we try to run `releases:retry`.

```
Cannot read property 'id' of null
Error: ENOENT: no such file or directory, open '/Users/tyranthosaur/.cache/heroku/error.log'
    at Object.openSync (fs.js:448:3)
    at Object.writeFileSync (fs.js:1210:35)
    at Object.appendFileSync (fs.js:1256:6)
    at log (/Users/tyranthosaur/.local/share/heroku/node_modules/heroku-cli-util/lib/errors.js:87:6)
    at handleErr (/Users/tyranthosaur/.local/share/heroku/node_modules/heroku-cli-util/lib/errors.js:102:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

I ran across this issue https://github.com/heroku/heroku-releases-retry/issues/6 but it seems unrelated as we have a lot of releases for the app we're trying to use this with.

**Comment by hugorut** [comment]
having this issue also

**Comment by dmathieu** [comment]
Can you run the command with `HEROKU_DEBUG=1` ?

**Comment by anthonator** [comment]
Is there a way I can share the result privately?

**Comment by dmathieu** [comment]
You can open a support ticket.

**Comment by jdxcode** [comment]
the error thing is a red herring, it just means it wasn't able to write the error out to the old log file. It can be fixed by updating heroku-cli-util, but it won't fix the actual problem—just the error logging.

**Comment by anthonator** [comment]
How do I update `heroku-cli-util` when the CLI is installed via homebrew?

**Comment by jdxcode** [comment]
you can't but if you just run `mkdir -p /Users/tyranthosaur/.cache/heroku` it will fix that logging error. Again, not fixing whatever the actual issue is.

**Comment by m1kola** [comment]
It looks like the issue we had with container apps. It doesn't look like there is an easy way to retry a release with container images on Heroku. You need to build and push a new image. I added some documentation in #11

**Comment by bbugh** [comment]
Does a review app count as a container app? We're getting this issue on our review apps as well, but we don't use containers.

**Comment by dmathieu** [comment]
Container apps are apps running on docker. Your review apps won't run on docker unless you're using `heroku.yml` configuration.
